Repo cleanup
w3c-ccg/vc-api-use-cases pull request #29
Opened 2023-03-14 18:43 UTC by eric-schuh

General respec and terms cleanup, some spelling/grammar updates

2023-03-14 18:51 UTC, TallTed requested changes
A few minor fixes to the fixes

2023-03-14 18:51 UTC, TallTed commented on index.html
> +        The VC-API address user needs in a number of key domains:
```suggestion
        The VC-API addresses user needs in a number of key domains:
```

2023-03-14 18:51 UTC, TallTed commented on terms.html
> +        a some set of <a>claims</a> made by the Issuer Coordinator about one or more subjects — to the Issuer Coordinator.
```suggestion
        some set of <a>claims</a> made by the Issuer Coordinator about one or more subjects — to the Issuer Coordinator. 
```

2023-03-14 18:51 UTC, TallTed commented on terms.html
> +    A representation of a set of tasks under the perview of a single <a>entity</a> which are indented to be implimentable seperately from other components.
```suggestion
    A representation of a set of tasks under the purview of a single <a>entity</a> which are indented to be implementable separately from other components. 
```

2023-03-28 20:04 UTC, merged

2023-03-28 20:04 UTC, jandrieu commented
Looks good. 

I think we'll want to make some policy choices about capitalization. I think Issuer, Verifier, and Holder are legitimate proper nouns, referring, e.g., to *the* Holder in a given interaction.

My thought is that when referring to the roles, that makes sense and is a bit of a different usage than my lazy overcapitalization of things like "method" in "DID method", which should not be capitalized (even though my fingers keep typing it that way.)

I'm sure there are other places to pay attention to that, but I'm going to merge. And add an issue.